import type { Metadata } from "next";
import { Geist, Geist_Mono, Fredoka } from "next/font/google";
import "./globals.css";

const fredokaOne = Fredoka({
  variable: "--font-fredoka-one",
  weight: '400', // Fredoka One has only one weight (400)
  subsets: ['latin'],
  display: 'swap', // Ensures the fallback font is used until Fredoka One loads
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fredokaOne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
